name:                nobs-server
version:             0.1.0.0
github:              "Soupstraw/NoBSPoker"
license:             AGPL-3.0-only
author:              "Joosep J채채ger"
maintainer:          "joosep.jaager@gmail.com"
copyright:           "2020 Joosep J채채ger"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/NoBSPoker#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- uniplate
- lens
- random-shuffle
- mtl
- vector
- MonadRandom
- wai
- warp
- websockets
- servant
- servant-blaze
- servant-server
- servant-websockets
- blaze-html
- bytestring
- base64

library:
  source-dirs: src

ghc-options:
  -Wall

executables:
  nobs-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nobs-server

tests:
  nobs-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NoBSPoker
